variables:
  RUN_TESTS: true
  RUN_LINTERS: true
  BUILD_STORYBOOK: false
  UI_BASELINE: false
  BUILD_ZOD: false
  PUBLISH_PACKAGE: false

include:
  - project: wallchain/devops/ci-templates
    ref: v1.3.0
    file:
      - next-js/pipelines/package-next-js.gitlab-ci.yaml
