services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:nightly-f6208d8db68f9acbe4ff8cd76958309efb61ea0b
    ports: [ "8545:8545" ]
    platform: linux/amd64
    entrypoint: [
      "anvil",
      "--host", "0.0.0.0",
      "--block-time", "1",
      "--silent",
      "--steps-tracing",
      "--fork-url", "https://eth-mainnet.nodereal.io/v1/104b7453b73041e5ac509697c21d463f",   # Romasku free nodereal eth mainnet
      "--fork-block-number", "20669000"  # Sep-03-2024 08:57:35 AM
#      "--fork-url", "https://go.getblock.io/df4af3f3a0db4af382f683fdd6e803dd",  # Romasku free getblock base
#      "--fork-block-number", "14500000"  # May-15-2024 04:09:07 PM
    ]
    healthcheck:
      test: [ "CMD", "cast", "block-number", "--rpc-url", "http://0.0.0.0:8545"]
      interval: 5s
      timeout: 1s
      retries: 2
    volumes:
      - foundry_data:/root/.foundry

  alto:
    image: ghcr.io/pimlicolabs/mock-alto-bundler:main
    ports: [ "4337:4337" ]
    environment:
      - ANVIL_RPC=http://anvil:8545
      - SKIP_DEPLOYMENTS=true
    entrypoint:
      - "/app/alto-entrypoint.sh"
    volumes:
      - "./alto-entrypoint.sh:/app/alto-entrypoint.sh"
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://0.0.0.0:4337/health" ]
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 30s
    depends_on:
      anvil:
        condition: service_healthy

  mock-paymaster:
    image: ghcr.io/pimlicolabs/mock-verifying-paymaster:main
    ports: [ "4330:3000" ]
    environment:
      - ALTO_RPC=http://alto:4337
      - ANVIL_RPC=http://anvil:8545

    depends_on:
      anvil:
        condition: service_healthy
      alto:
        condition: service_healthy
volumes:
  foundry_data:

